/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ContactInfoRouteImport } from './routes/contact-info'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BagRouteImport } from './routes/bag'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as AccountDetailsRouteImport } from './routes/account.details'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactInfoRoute = ContactInfoRouteImport.update({
  id: '/contact-info',
  path: '/contact-info',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BagRoute = BagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountDetailsRoute = AccountDetailsRouteImport.update({
  id: '/account/details',
  path: '/account/details',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/careers': typeof CareersRoute
  '/contact-info': typeof ContactInfoRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/account/details': typeof AccountDetailsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/careers': typeof CareersRoute
  '/contact-info': typeof ContactInfoRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/account/details': typeof AccountDetailsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account': typeof AccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bag': typeof BagRoute
  '/careers': typeof CareersRoute
  '/contact-info': typeof ContactInfoRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/account/details': typeof AccountDetailsRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/product/$handle': typeof ProductHandleRoute
  '/account/': typeof AccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bag'
    | '/careers'
    | '/contact-info'
    | '/signup'
    | '/verify'
    | '/account/details'
    | '/collection/$slug'
    | '/product/$handle'
    | '/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bag'
    | '/careers'
    | '/contact-info'
    | '/signup'
    | '/verify'
    | '/account/details'
    | '/collection/$slug'
    | '/product/$handle'
    | '/account'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bag'
    | '/careers'
    | '/contact-info'
    | '/signup'
    | '/verify'
    | '/account/details'
    | '/collection/$slug'
    | '/product/$handle'
    | '/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BagRoute: typeof BagRoute
  CareersRoute: typeof CareersRoute
  ContactInfoRoute: typeof ContactInfoRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  AccountDetailsRoute: typeof AccountDetailsRoute
  CollectionSlugRoute: typeof CollectionSlugRoute
  ProductHandleRoute: typeof ProductHandleRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-info': {
      id: '/contact-info'
      path: '/contact-info'
      fullPath: '/contact-info'
      preLoaderRoute: typeof ContactInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bag': {
      id: '/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof BagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/details': {
      id: '/account/details'
      path: '/account/details'
      fullPath: '/account/details'
      preLoaderRoute: typeof AccountDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BagRoute: BagRoute,
  CareersRoute: CareersRoute,
  ContactInfoRoute: ContactInfoRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  AccountDetailsRoute: AccountDetailsRoute,
  CollectionSlugRoute: CollectionSlugRoute,
  ProductHandleRoute: ProductHandleRoute,
  AccountIndexRoute: AccountIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
